### ISSUE TITLE
Livechan is down, we need a moderator for /v and Fredrick "Hotwheels" Brennan wants to get in touch.

### ISSUE THREAD

**Issue by Dagrotwiffdabigchoppa** [emgram769/live4chan#137]
What the title says, the site is currently down due to what is presumably a great deal of strain and the owner of 8chan wants to get into contact (last I heard) about the project. We also need a new mod/janitor for /v as great as the greek is at his job Ellas is not on enough of the time, it would be easier if we could get our own moderator or janitor to help keep the place clean from the spam.

**Comment by emgram769** [comment]
I'm trying to get the site back up but a simple restart doesn't seem to be doing the trick.  I'd be glad to give /v another mod once I get the site up and running again.  Hotwheels can contact me at mod.livechan@gmail.com if he'd like.

**Comment by emgram769** [comment]
alright it should be back up now, but the server is not gonna be able to handle a big load. do you recall the user count before it went down?

**Comment by Elemarkef** [comment]
125 users at the time it went down, but we were at about 200 at peak.

**Comment by Dagrotwiffdabigchoppa** [comment]
For the mod position do we just email you? If so, sent to the account Livechanv@8chan.co

**Comment by emgram769** [comment]
yep that sounds good

**Comment by Dagrotwiffdabigchoppa** [comment]
Great, sending you the info now then.

**Comment by an969567** [comment]
test
